#!/bin/bash
# WynlandOS - stage the base userland: GNU coreutils, fish and friends.
#
# Ubuntu's prebuilt packages (glibc, like Qt): the .debs below are fetched
# with `apt-get download` into a cache and unpacked there, then
# build/base_manifest.txt lists
#   - every file of them except docs, man pages and translations
#     (gnu-coreutils' "gnuls" etc. under their plain names),
#   - their symlinks, plus /bin -> usr/bin and /bin/sh -> dash,
#   - the ldd closure of the binaries, minus what the other manifests ship.
#
# usage: tools/stage_base.sh            (from the repo root, inside WSL)
set -euo pipefail
cd "$(dirname "$0")/.."
REPO=$PWD
CACHE=${BASE_CACHE:-$HOME/.cache/wynland-base}
ROOT=$CACHE/root
OUT=$REPO/build
MAN=$OUT/base_manifest.txt

PKGS="gnu-coreutils fish fish-common dash grep sed less findutils tar gzip
 xz-utils bzip2 diffutils debianutils ncurses-base ncurses-bin bsdextrautils
 file libmagic1t64 libmagic-mgc procps psmisc util-linux hostname"

# 1. fetch + unpack (each package into its own dir: we ship packages, not
#    whatever else the host would have)
mkdir -p "$CACHE/debs" "$ROOT"
for p in $PKGS; do
    if ! ls "$CACHE/debs/${p}_"*.deb >/dev/null 2>&1; then
        (cd "$CACHE/debs" && apt-get download "$p" >/dev/null 2>&1) || echo "  BASE       (no package $p)"
    fi
done
stamp=$(ls "$CACHE"/debs/*.deb | md5sum | cut -c1-8)
if [ "$(cat "$CACHE/.unpacked" 2>/dev/null)" != "$stamp" ]; then
    rm -rf "$ROOT"; mkdir -p "$ROOT"
    for d in "$CACHE"/debs/*.deb; do dpkg-deb -x "$d" "$ROOT"; done
    echo "$stamp" > "$CACHE/.unpacked"
fi
echo "  BASE       $(ls "$CACHE"/debs/*.deb | wc -l) packages from $CACHE"

skip() {
    case "$1" in
        /usr/share/doc/*|/usr/share/man/*|/usr/share/locale/*|/usr/share/info/*) return 0 ;;
        /usr/share/lintian/*|/usr/share/bug/*|/usr/share/menu/*|/usr/share/doc-base/*) return 0 ;;
        /usr/share/fish/man/*|/usr/share/fish/tools/*|/usr/share/applications/*) return 0 ;;
        /usr/share/pixmaps/*|/usr/share/icons/*|/etc/init.d/*|/etc/cron*|/usr/lib/systemd/*) return 0 ;;
        /usr/lib/x86_64-linux-gnu/*.so*) return 0 ;;   # libraries go by soname below
        /lib/systemd/*|/usr/share/bash-completion/*|/usr/share/zsh/*) return 0 ;;
    esac
    return 1
}
# gnu-coreutils names its tools gnuls, gnu[ ...: ship them as ls, [ ...
plain() {
    case "$1" in
        /usr/bin/gnu*|/usr/sbin/gnu*) local d=${1%/*}; echo "$d/${1#$d/gnu}" ;;
        *) echo "$1" ;;
    esac
}

dirs=$(mktemp); files=$(mktemp); links=$(mktemp)
for d in "$CACHE"/debs/*.deb; do
    dpkg-deb -c "$d" | while read -r mode _ _ _ _ path rest; do
        path=${path#.}
        [ -z "$path" ] || [ "$path" = / ] && continue
        path=${path%/}
        skip "$path" && continue
        case "$mode" in
            d*) echo "$path" >> "$dirs" ;;
            l*) echo "$(plain "$path") ${rest#-> }" >> "$links" ;;
            -*) echo "$path" >> "$files" ;;
        esac
    done
done

BINS=""
{
    echo "# generated by tools/stage_base.sh -- do not edit"
    # usrmerge: /bin is usr/bin. /sbin, /lib and /lib64 are real dirs here
    echo "S /bin usr/bin"
    for d in $(sort -u "$dirs"); do
        case "$d" in /bin|/bin/*|/sbin|/lib|/lib64) continue ;; esac
        skip "$d/x" && continue
        echo "D $d"
    done
    sort -u "$files" | while read -r f; do
        echo "F $(plain "$f") $ROOT$f"
    done
    sort -u "$links" | while read -r l t; do
        case "$l" in /bin|/bin/*|/usr/lib/x86_64-linux-gnu/*.so*) continue ;; esac
        echo "S $l $t"
    done
    grep -q '^/usr/bin/sh ' "$links" || echo "S /usr/bin/sh dash"
    grep -q '^/usr/bin/which ' "$links" || echo "S /usr/bin/which which.debianutils"
} > "$MAN"

# one line per path; drop dirs the other manifests make
OTHER="ext2_manifest.txt"
for m in qt6 gst wpe; do [ -f "$OUT/${m}_manifest.txt" ] && OTHER="$OTHER $OUT/${m}_manifest.txt"; done
python3 - "$MAN" $OTHER <<'EOF'
import sys
man, others = sys.argv[1], sys.argv[2:]
have = set()
for o in others:
    for line in open(o):
        p = line.split()
        if len(p) >= 2 and p[0] == "D": have.add(p[1])
lines = open(man).read().splitlines()
out, seen = [], set()
for l in lines:
    p = l.split()
    if p and p[0] in ("D", "F", "S"):
        if p[1] in seen or (p[0] == "D" and p[1] in have): continue
        seen.add(p[1])
    out.append(l)
open(man, "w").write("\n".join(out) + "\n")
EOF

# 2. libraries: the ldd closure of every ELF shipped, by soname into /lib64
ELFS=$(awk '$1=="F" {print $3}' "$MAN" | while read -r f; do
    if head -c4 "$f" | grep -q ELF; then echo "$f"; fi; done)
for f in $ELFS; do
    LD_LIBRARY_PATH="$ROOT/usr/lib/x86_64-linux-gnu" ldd "$f" 2>/dev/null | awk '/=>/ && $3 ~ /^\// {print $1, $3}' || true
done | sort -u | while read -r soname path; do
    if awk -v want="/lib64/$soname" '($1=="F"||$1=="Fo") && $2==want {found=1} END {exit !found}' $OTHER; then continue; fi
    echo "F /lib64/$soname $(readlink -f "$path")"
done | sort -u >> "$MAN"

missing=$(for f in $ELFS; do LD_LIBRARY_PATH="$ROOT/usr/lib/x86_64-linux-gnu" ldd "$f" 2>/dev/null | grep 'not found' || true; done | sort -u)
if [ -n "$missing" ]; then echo "  BASE       WARNING: unresolved:"; echo "$missing"; fi

# 3. config + the autotest check (rootfs/etc/wynrc/services/shtest)
{
    echo "F /etc/fish/conf.d/wynland.fish $REPO/rootfs/etc/fish/conf.d/wynland.fish"
    echo "F /shtest.elf $OUT/shtest.elf"
    echo "F /etc/wynrc/services/shtest $REPO/rootfs/etc/wynrc/services/shtest"
} >> "$MAN"
grep -q '^D /etc/fish$' "$MAN" || echo "D /etc/fish" >> "$MAN"
grep -q '^D /etc/fish/conf.d$' "$MAN" || echo "D /etc/fish/conf.d" >> "$MAN"

rm -f "$dirs" "$files" "$links"
echo "  BASE       $(grep -c '^F' "$MAN") files, $(grep -c '^S' "$MAN") links in $MAN"
