#!/bin/bash
# WynlandOS - stage GStreamer for the image.
#
# Ubuntu's prebuilt GStreamer (glibc, like Qt): the .debs of the packages
# below and every dependency the host does not have installed are fetched
# with `apt-get download` into a cache and unpacked there. Then:
#   - test media is made on the host with that same GStreamer
#     (build/media/: a tone in Ogg Vorbis, a clip in MP4 or Matroska),
#   - build/gst_manifest.txt lists the tools, a chosen set of plugins and
#     the ldd closure of all of it, minus what the other manifests ship.
#
# usage: tools/stage_gst.sh            (from the repo root, inside WSL)
set -euo pipefail
cd "$(dirname "$0")/.."
REPO=$PWD
CACHE=${GST_CACHE:-$HOME/.cache/wynland-gst}
ROOT=$CACHE/root
LIB=$ROOT/usr/lib/x86_64-linux-gnu
PLUG=$LIB/gstreamer-1.0
OUT=$REPO/build
MAN=$OUT/gst_manifest.txt

TOP="libgstreamer1.0-0 gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-libav"
# host side only, to make the H.264 test clip (x264enc); not shipped
HOST_ONLY="gstreamer1.0-plugins-ugly"

# 1. fetch + unpack: the packages and every dependency missing on the host
mkdir -p "$CACHE/debs" "$ROOT"
deps=$(apt-cache depends --recurse --no-recommends --no-suggests --no-conflicts \
           --no-breaks --no-replaces --no-enhances $TOP $HOST_ONLY 2>/dev/null \
       | grep -v '^ ' | grep -v '^<' | sort -u)
NEW=0
for p in $deps; do
    if dpkg-query -W -f='${Status}' "$p" 2>/dev/null | grep -q 'install ok installed'; then
        case " $TOP $HOST_ONLY " in *" $p "*) ;; *) continue ;; esac
    fi
    if ! ls "$CACHE/debs/${p}_"*.deb >/dev/null 2>&1; then
        (cd "$CACHE/debs" && apt-get download "$p" >/dev/null 2>&1) || echo "  GST        (no package $p)"
        NEW=1
    fi
done
if [ $NEW = 1 ] || [ ! -f "$CACHE/.unpacked" ]; then
    for d in "$CACHE"/debs/*.deb; do dpkg-deb -x "$d" "$ROOT"; done
    touch "$CACHE/.unpacked"
fi
echo "  GST        GStreamer $(ls "$CACHE"/debs/libgstreamer1.0-0_*.deb | sed 's/.*_\([0-9.]*\)-.*/\1/') from $CACHE"

# the cached GStreamer, runnable on the host
gst_env() {
    env LD_LIBRARY_PATH="$LIB:$LIB/pulseaudio" \
        GST_PLUGIN_SYSTEM_PATH="$PLUG" \
        GST_PLUGIN_SCANNER="$LIB/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner" \
        GST_REGISTRY="$CACHE/registry.bin" "$@"
}
LAUNCH="$ROOT/usr/bin/gst-launch-1.0"

# 2. test media
MEDIA=$OUT/media
mkdir -p "$MEDIA"
if [ ! -s "$MEDIA/tone.ogg" ]; then
    gst_env "$LAUNCH" -q audiotestsrc freq=440 volume=0.3 num-buffers=130 \
        ! audioconvert ! vorbisenc ! oggmux ! filesink location="$MEDIA/tone.ogg"
fi
if [ ! -s "$MEDIA/clip.mp4" ] && [ ! -s "$MEDIA/clip.mkv" ]; then
    # web-like: H.264 + AAC in MP4; MPEG-4 Part 2 + Vorbis in Matroska if
    # there is no H.264 encoder
    if gst_env "$ROOT/usr/bin/gst-inspect-1.0" x264enc >/dev/null 2>&1; then
        gst_env "$LAUNCH" -q mp4mux name=m ! filesink location="$MEDIA/clip.mp4" \
            videotestsrc num-buffers=90 ! video/x-raw,width=320,height=240,framerate=30/1 \
            ! videoconvert ! x264enc ! queue ! m. \
            audiotestsrc freq=880 volume=0.3 num-buffers=130 ! audioconvert ! avenc_aac ! aacparse ! queue ! m.
    else
        gst_env "$LAUNCH" -q matroskamux name=m ! filesink location="$MEDIA/clip.mkv" \
            videotestsrc num-buffers=90 ! video/x-raw,width=320,height=240,framerate=30/1 \
            ! videoconvert ! avenc_mpeg4 ! queue ! m. \
            audiotestsrc freq=880 volume=0.3 num-buffers=130 ! audioconvert ! vorbisenc ! queue ! m.
    fi
fi
CLIP=$(ls "$MEDIA"/clip.* | head -1)
echo "  GST        test media: $(basename "$MEDIA/tone.ogg") $(basename "$CLIP")"

# 3. what ships: tools, the scanner, chosen plugins
PLUGINS="coreelements
 playback typefindfunctions app audioconvert audioresample audiorate volume
 videoconvertscale videorate audiotestsrc videotestsrc rawparse pbtypes
 ogg vorbis opus
 ossaudio wavparse matroska isomp4 autodetect audioparsers id3demux
 libav"
SHIP=""
for p in $PLUGINS; do
    f="$PLUG/libgst$p.so"
    if [ -f "$f" ]; then SHIP="$SHIP $f"; else echo "  GST        WARNING: no plugin $p"; fi
done
TOOLS="$ROOT/usr/bin/gst-launch-1.0 $ROOT/usr/bin/gst-inspect-1.0"
SCANNER="$LIB/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"

{
    echo "# generated by tools/stage_gst.sh -- do not edit"
    # libgstreamer is relocatable: it takes the plugins from next to
    # itself (/lib64/gstreamer-1.0) and the scanner from
    # <its dir>/../../lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0
    # (Ubuntu's libdir and libexecdir, made relative)
    echo "D /lib64/gstreamer-1.0"
    echo "D /lib/x86_64-linux-gnu"
    echo "D /lib/x86_64-linux-gnu/gstreamer1.0"
    echo "D /lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0"
    echo "F /lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner $SCANNER"
    for t in $TOOLS; do echo "F /usr/bin/$(basename "$t") $t"; done
    for f in $SHIP; do echo "F /lib64/gstreamer-1.0/$(basename "$f") $f"; done
    echo "D /usr/share/wynland"
    echo "D /usr/share/wynland/media"
    echo "F /usr/share/wynland/media/tone.ogg $MEDIA/tone.ogg"
    echo "F /usr/share/wynland/media/$(basename "$CLIP") $CLIP"
    # the autotest check (rootfs/etc/wynrc/services/gsttest, AUTOTEST=1)
    echo "F /gsttest.elf $OUT/gsttest.elf"
    echo "F /etc/wynrc/services/gsttest $REPO/rootfs/etc/wynrc/services/gsttest"
} > "$MAN"

# 4. libraries: the ldd closure, by soname into /lib64, minus what the
#    base and Qt manifests already ship
OTHER="ext2_manifest.txt"
[ -f "$OUT/qt6_manifest.txt" ] && OTHER="$OTHER $OUT/qt6_manifest.txt"
for f in $TOOLS $SCANNER $SHIP; do
    gst_env ldd "$f" | awk '/=>/ && $3 ~ /^\// {print $1, $3}'
done | sort -u | while read soname path; do
    # fixed strings: sonames like libstdc++ are not regexes
    if awk -v want="/lib64/$soname" '($1=="F"||$1=="Fo") && $2==want {found=1} END {exit !found}' $OTHER; then continue; fi
    echo "F /lib64/$soname $(readlink -f "$path")"
done | sort -u >> "$MAN"

missing=$(for f in $TOOLS $SCANNER $SHIP; do gst_env ldd "$f" | grep 'not found' || true; done | sort -u)
if [ -n "$missing" ]; then echo "  GST        WARNING: unresolved:"; echo "$missing"; fi
echo "  GST        $(grep -c '^F' "$MAN") files in $MAN"
